+ чтение контейнеров в потоках
Infactum/onec_dtools pull request #5
Opened 2018-09-03 11:15 UTC by pruidzeko

Добавил многопоточности при распаковке cf-ников.

На локальной машине, при распаковке ERP2 результат выглядит так: 
было ~12 мин, стало ~3 мин.

2018-09-03 12:40 UTC, Infactum requested changes
Идея в целом хорошая, но функционал должен быть опциональным.

2018-09-03 12:40 UTC, Infactum commented on onec_dtools/container_reader.py
> +        # ждём окончания записи всех потоков этого уровня..
https://docs.python.org/3/library/threading.html#threading.Thread.join

2018-09-03 12:40 UTC, Infactum commented on onec_dtools/container_reader.py
> +            threads.append(async_writer)
Количество потоков нужно ограничивать. Обычно поток на ядро.

2018-09-03 16:18 UTC, pruidzeko commented on onec_dtools/container_reader.py
> +            threads.append(async_writer)
Это не процессы. Потоки (треды) ограничивать особой необходимости нет - судя по профилированию все отрабатывает довольно быстро и закрывается - 4 ядра более чем 30% не загружаются при парсинге ERP2. Экстраполируя на 2 ядра - это ~60% загрузки.
Потом GIL особо разойтись тоже не даст. 
ИМХО, код управления количеством одновременных тредов, мне кажется, напротив, может загрузить CPU больше, чем параллельная запись в таком режиме.. тут скорее диск будет "бутылочным" горлышком, а не количество потоков.

2018-09-03 16:26 UTC, pruidzeko commented on onec_dtools/container_reader.py
> +        # ждём окончания записи всех потоков этого уровня..
С этим методом я знаком и там возникли проблемы - на следующей строке, после метода async_writer.run() - ставим join - но поток оказывается уже отработавшим.. соответственно join() к неактивному (отработавшему) потоку выкидывает ошибку - он не применим к закончившим работу потокам.

Была версия через try / except с join - но скорость была меньше, чем при текущем подходе.

2018-09-15 10:12 UTC, Infactum commented
Текущий механизм библиотеки работает с минимальным потреблением ресурсов - поэтому оставлю все как есть.
Для ситуаций, когда нужно максимально быстро выполнить распаковку добавил иллюстрирующий пример в 99c0b394f51fbd4225735ab37068c2dae00fdc00.

2018-09-15 10:12 UTC, closed without merging